# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: sutinee
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: worktimes_development

test:
  <<: *default
  database: worktimes_test

production:
  <<: *default
  database: worktimes_production
  username: sutinee
  password: <%= ENV['ATIMES_DATABASE_PASSWORD'] %>
